// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pilegoblin/garbanzo/ent/bean"
)

// Bean is the model entity for the Bean schema.
type Bean struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BeanQuery when eager-loading is set.
	Edges        BeanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BeanEdges holds the relations/edges for other nodes in the graph.
type BeanEdges struct {
	// Posts holds the value of the posts edge.
	Posts []*Post `json:"posts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostsOrErr returns the Posts value or an error if the edge
// was not loaded in eager-loading.
func (e BeanEdges) PostsOrErr() ([]*Post, error) {
	if e.loadedTypes[0] {
		return e.Posts, nil
	}
	return nil, &NotLoadedError{edge: "posts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bean) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bean.FieldID:
			values[i] = new(sql.NullInt64)
		case bean.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bean fields.
func (b *Bean) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bean.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int(value.Int64)
		case bean.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				b.Name = value.String
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bean.
// This includes values selected through modifiers, order, etc.
func (b *Bean) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// QueryPosts queries the "posts" edge of the Bean entity.
func (b *Bean) QueryPosts() *PostQuery {
	return NewBeanClient(b.config).QueryPosts(b)
}

// Update returns a builder for updating this Bean.
// Note that you need to call Bean.Unwrap() before calling this method if this Bean
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Bean) Update() *BeanUpdateOne {
	return NewBeanClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Bean entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Bean) Unwrap() *Bean {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bean is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Bean) String() string {
	var builder strings.Builder
	builder.WriteString("Bean(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("name=")
	builder.WriteString(b.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Beans is a parsable slice of Bean.
type Beans []*Bean
