// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pilegoblin/garbanzo/ent/bean"
	"github.com/pilegoblin/garbanzo/ent/pod"
	"github.com/pilegoblin/garbanzo/ent/post"
)

// BeanCreate is the builder for creating a Bean entity.
type BeanCreate struct {
	config
	mutation *BeanMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (bc *BeanCreate) SetName(s string) *BeanCreate {
	bc.mutation.SetName(s)
	return bc
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (bc *BeanCreate) AddPostIDs(ids ...int) *BeanCreate {
	bc.mutation.AddPostIDs(ids...)
	return bc
}

// AddPosts adds the "posts" edges to the Post entity.
func (bc *BeanCreate) AddPosts(p ...*Post) *BeanCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bc.AddPostIDs(ids...)
}

// SetPodID sets the "pod" edge to the Pod entity by ID.
func (bc *BeanCreate) SetPodID(id int) *BeanCreate {
	bc.mutation.SetPodID(id)
	return bc
}

// SetNillablePodID sets the "pod" edge to the Pod entity by ID if the given value is not nil.
func (bc *BeanCreate) SetNillablePodID(id *int) *BeanCreate {
	if id != nil {
		bc = bc.SetPodID(*id)
	}
	return bc
}

// SetPod sets the "pod" edge to the Pod entity.
func (bc *BeanCreate) SetPod(p *Pod) *BeanCreate {
	return bc.SetPodID(p.ID)
}

// Mutation returns the BeanMutation object of the builder.
func (bc *BeanCreate) Mutation() *BeanMutation {
	return bc.mutation
}

// Save creates the Bean in the database.
func (bc *BeanCreate) Save(ctx context.Context) (*Bean, error) {
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BeanCreate) SaveX(ctx context.Context) *Bean {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BeanCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BeanCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BeanCreate) check() error {
	if _, ok := bc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Bean.name"`)}
	}
	if v, ok := bc.mutation.Name(); ok {
		if err := bean.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Bean.name": %w`, err)}
		}
	}
	return nil
}

func (bc *BeanCreate) sqlSave(ctx context.Context) (*Bean, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BeanCreate) createSpec() (*Bean, *sqlgraph.CreateSpec) {
	var (
		_node = &Bean{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(bean.Table, sqlgraph.NewFieldSpec(bean.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(bean.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := bc.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bean.PostsTable,
			Columns: []string{bean.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.PodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bean.PodTable,
			Columns: []string{bean.PodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pod_beans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BeanCreateBulk is the builder for creating many Bean entities in bulk.
type BeanCreateBulk struct {
	config
	err      error
	builders []*BeanCreate
}

// Save creates the Bean entities in the database.
func (bcb *BeanCreateBulk) Save(ctx context.Context) ([]*Bean, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Bean, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BeanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BeanCreateBulk) SaveX(ctx context.Context) []*Bean {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BeanCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BeanCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
